error fix, bytes-like object:
PacGAN\stacked_MNIST_experiments\VEEGAN_experiment\model.py", line 156, in train
    writer.writeheader()
...
TypeError: a bytes-like object is required, not 'str'